/**
 * resolveKmbTopology — resolves KMB route/stop data with a layered fallback.
 *
 * Priority chain:
 *   1. AsyncStorage cache (freshest network data from a previous session)
 *   2. Bundled snapshot (src/data/kmb.json — generated at build time)
 *   3. Live network fetch (background refresh)
 *
 * Network failure at any layer never causes an error for the caller.
 * The function always returns usable topology, falling back to the next
 * available layer.
 */
import AsyncStorage from '@react-native-async-storage/async-storage';
import type { Stop, RouteStopLink } from '@/src/journey/providers/types';
import * as kmbAPI from '@/src/services/kmbAPI';

const KMB_CACHE_KEY = '@hk-transit-ai/kmb-topology-v2';

export interface KmbTopology {
  stops: Stop[];
  links: RouteStopLink[];
  source: 'cache' | 'bundled' | 'network';
  cachedAt: string | null;
}

let bundledSnapshot: KmbTopology | null = null;

/** Load the bundled KMB snapshot (lazy, cached in module scope). */
async function loadBundled(): Promise<KmbTopology | null> {
  if (bundledSnapshot) return bundledSnapshot;
  try {
    // Dynamic import of the bundled JSON snapshot generated by data:refresh
    const mod = await import('@/src/data/kmb.json');
    const raw = (mod as any).default || mod;
    const stops: Stop[] = (raw.stops || []).map((s: any) => ({
      stopId: s.stopId || s.stop,
      name_en: s.name_en || '',
      name_tc: s.name_tc || '',
      name_sc: s.name_sc || '',
      lat: Number(s.lat),
      lng: Number(s.lng || s.long),
      provider: 'KMB' as const,
    }));
    const links: RouteStopLink[] = (raw.routeStops || raw.links || []).map((l: any) => ({
      route: l.route,
      bound: l.bound,
      seq: Number(l.seq),
      stopId: l.stopId || l.stop,
      provider: 'KMB' as const,
    }));
    if (stops.length === 0) return null;
    bundledSnapshot = { stops, links, source: 'bundled', cachedAt: raw.generatedAt || null };
    return bundledSnapshot;
  } catch {
    return null;
  }
}

/** Fetch live KMB topology from the network. */
async function fetchNetwork(): Promise<KmbTopology> {
  const [stops, routeStops] = await Promise.all([
    kmbAPI.fetchAllStops(),
    kmbAPI.fetchAllRouteStops(),
  ]);
  const topology: KmbTopology = {
    stops: stops.map((s) => ({
      stopId: s.stop,
      name_en: s.name_en,
      name_tc: s.name_tc,
      name_sc: (s as any).name_sc || '',
      lat: Number(s.lat),
      lng: Number(s.long),
      provider: 'KMB' as const,
    })),
    links: routeStops.map((l) => ({
      route: l.route,
      bound: l.bound,
      seq: Number(l.seq),
      stopId: l.stop,
      provider: 'KMB' as const,
    })),
    source: 'network' as const,
    cachedAt: new Date().toISOString(),
  };

  // Persist to AsyncStorage for faster startup next time
  AsyncStorage.setItem(KMB_CACHE_KEY, JSON.stringify(topology)).catch(() => undefined);
  return topology;
}

/** Read previously-cached topology from AsyncStorage. */
async function loadCache(): Promise<KmbTopology | null> {
  try {
    const raw = await AsyncStorage.getItem(KMB_CACHE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as KmbTopology;
    if (!parsed.stops || parsed.stops.length === 0) return null;
    return { ...parsed, source: 'cache' };
  } catch {
    return null;
  }
}

/**
 * Resolve KMB topology with layered fallback.
 *
 * Returns usable topology immediately (cache or bundled), then fires a
 * background network refresh. The returned promise resolves as soon as
 * ANY layer is available — it does NOT wait for the network.
 *
 * If ALL layers fail, the promise rejects.
 */
export async function resolveKmbTopology(): Promise<{
  topology: KmbTopology;
  ready: Promise<void>; // resolves when background refresh completes (or fails silently)
}> {
  // Layer 1: AsyncStorage cache (fastest)
  const cached = await loadCache();
  if (cached) {
    // Fire background refresh, but return immediately
    const ready = fetchNetwork()
      .then(() => undefined)
      .catch(() => undefined);
    return { topology: cached, ready };
  }

  // Layer 2: Bundled snapshot
  const bundled = await loadBundled();
  if (bundled) {
    // Fire background refresh
    const ready = fetchNetwork()
      .then(() => undefined)
      .catch(() => undefined);
    return { topology: bundled, ready };
  }

  // Layer 3: Network (last resort — must succeed)
  const network = await fetchNetwork();
  return { topology: network, ready: Promise.resolve() };
}

/**
 * Lightweight check: can we get ANY KMB data (cache or bundled)?
 * Returns true immediately without network. Used to decide whether
 * to show "data unavailable" UI.
 */
export async function hasKmbFallback(): Promise<boolean> {
  const cached = await loadCache();
  if (cached) return true;
  const bundled = await loadBundled();
  return bundled !== null;
}
